export interface Images {
  Containers: number;
  Created: number;
  Id: string;
  Labels?: Labels;
  ParentId: string;
  RepoDigests?: (string)[] | null;
  RepoTags?: (string)[] | null;
  SharedSize: number;
  Size: number;
  VirtualSize: number;
}
export interface Labels {
  [k: string]: string
  // architecture?: string | null;
  // 'build-date'?: string | null;
  // 'com.redhat.build-host'?: string | null;
  // 'com.redhat.component'?: string | null;
  // 'com.redhat.deployments-dir'?: string | null;
  // 'com.redhat.dev-mode'?: string | null;
  // 'com.redhat.dev-mode.port'?: string | null;
  // 'com.redhat.license_terms'?: string | null;
  // description?: string | null;
  // 'distribution-scope'?: string | null;
  // help?: string | null;
  // 'io.buildpacks.stack.id'?: string | null;
  // 'io.k8s.description'?: string | null;
  // 'io.k8s.display-name'?: string | null;
  // 'io.openshift.expose-services'?: string | null;
  // 'io.openshift.s2i.scripts-url'?: string | null;
  // 'io.openshift.tags'?: string | null;
  // 'io.s2i.scripts-url'?: string | null;
  // maintainer?: string | null;
  // name?: string | null;
  // release?: string | null;
  // summary?: string | null;
  // url?: string | null;
  // usage?: string | null;
  // 'vcs-ref'?: string | null;
  // 'vcs-type'?: string | null;
  // vendor?: string | null;
  // version?: string | null;
  // 'org.label-schema.build-date'?: string | null;
  // 'org.label-schema.license'?: string | null;
  // 'org.label-schema.name'?: string | null;
  // 'org.label-schema.schema-version'?: string | null;
  // 'org.label-schema.vendor'?: string | null;
  // 'org.opencontainers.image.created'?: string | null;
  // 'org.opencontainers.image.licenses'?: string | null;
  // 'org.opencontainers.image.title'?: string | null;
  // 'org.opencontainers.image.vendor'?: string | null;
  // authors?: string | null;
  // 'org.label-schema.arch'?: string | null;
  // 'org.label-schema.description'?: string | null;
  // 'org.label-schema.docker.dockerfile'?: string | null;
  // 'org.label-schema.url'?: string | null;
  // 'org.label-schema.vcs-ref'?: string | null;
  // 'org.label-schema.vcs-type'?: string | null;
  // 'org.label-schema.vcs-url'?: string | null;
  // 'org.label-schema.version'?: string | null;
  // Description?: string | null;
  // Version?: string | null;
  // 'io.webdevops.layout'?: string | null;
  // 'io.webdevops.version'?: string | null;
  // 'io.buildah.version'?: string | null;
  // 'os.version'?: string | null;
  // 'postgresql.version'?: string | null;
  // 'postgresql.version.major'?: string | null;
  // 'license'?: string | null;
}
